<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNpu1BKG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNpu1BKG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNpu1BKG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNpu1BKG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNpu1BKG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Npu1BKG',
    'container.build_id' => '608c1458',
    'container.build_time' => 1638870393,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNpu1BKG');
